---
version: '3.7'
services:
  mysql:
    image: egova.top:30004/egova/mysql:8.0.18
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - ingress
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: api
      # 不能是root
      MYSQL_USER: api
      MYSQL_PASSWORD: egova@2020!
      MYSQL_ROOT_PASSWORD: egova@2020!
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_bin
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_connections=1000
      --max_allowed_packet=128M
    volumes:
      - /egova/docker/volumes/mysql/data:/var/lib/mysql
  redis:
    image: egova.top:30004/egova/redis:5.0.7
    container_name: redis
    restart: always
    command: redis-server /etc/redis/conf/redis.conf
    environment:
      TZ: Asia/Shanghai
    ports:
      - 6379:6379
    networks:
      - ingress
    volumes:
      - /egova/docker/volumes/redis:/data
networks:
  ## 网络组名称
  ingress:
    external:
      name: egova-network
